spec:
  containerConcurrency: 80
  timeoutSeconds: 20
    env:
    - name: SMTP_SERVER
      value: smtp.gmail.com
    - name: SMTP_PORT
      value: 587
    - name: SMTP_USER
      value: richardcunningham691@gmail.com
    - name: SMTP_PASSWORD
      value: qyumgadxetzlzmzb
    - name: CONTACT_RECEIVER
      value: richardcunningham691@gmail.com
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
